SELECT TOP (100) [Barcode]
            ,[Brand]
            ,[BuyingPackage]
            ,[Color]
            ,[IsChillerStock]
            ,[LeadTimeDays]
            ,[LineageKey]
            ,[Photo]
            ,[QuantityPerOuter]
            ,[RecommendedRetailPrice]
            ,[SellingPackage]
            ,[Size]
            ,[StockItem]
            ,[StockItemKey]
            ,[TaxRate]
            ,[TypicalWeightPerUnit]
            ,[UnitPrice]
            ,[ValidFrom]
            ,[ValidTo]
            ,[WWIStockItemID]
FROM [Fabricbookdw].[dbo].[dimension_stock_item]